#!/bin/bash

ROOT=$(git rev-parse --show-toplevel)
ESLINT="$ROOT/node_modules/.bin/eslint"
LOG="$SCRIPTPATH/../eslint.log"
LAST_COMMIT_MSG=$(cat $1 | grep "WIP:" | wc -l)

red=$(tput setaf 1)
magenta=$(tput setaf 5)
gold=$(tput setaf 3)
default=$(tput sgr0)

if [ ${LAST_COMMIT_MSG[*]} -gt 0 ]; then
  printf "WIP it GOOD!"
  exit 0
else
  # Check for eslint
  if [[ ! -x "$ESLINT" ]]; then
    printf "${red}\nESlint Is Required to perform linting\n\n${default} Run ${gold}[${magenta}yarn add --dev eslint${gold}]${default} to install\n\n"
    exit 1
  fi

  PASS=true

  yarn lint;

  if [[ "$?" == 1 ]]; then
    PASS=false
  fi

  if $PASS; then
    printf "${magenta}\nProceeding with Commit${default}\n"
    exit 0
  else
    printf "${red}\n\nLINTING FAILED\n\nCOMMIT ABORTED\n\n${default}Run ${gold}[${magenta}npm run lint${gold}]${default} for more details.\n\n"
    exit 1
  fi
fi