version: '3.8'

services:
  pgdb:
    container_name: pgdb_savannah_info
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web_server:
    build: .
    container_name: backend_api
    volumes:
      - ./backend:/backend_api
    ports:
      - "8000:8000"
  
