version: '3.8'

services:
  pgdb:
    container_name: pgdb_savannah_info
    image: postgres
    restart: always
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  
