name: Frontend CI

on:
  push:
    branches:
      - development
      - production

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.0

      - name: Navigate to frontend folder
        run: cd frontend/

      - name: Install dependencies
        run: yarn install
        working-directory: frontend/

      - name: Install Husky
        run: yarn add husky --dev
        working-directory: frontend/

      - name: Install Git hooks
        run: npx husky install
        working-directory: frontend/

      - name: Run linting
        run: yarn lint
        working-directory: frontend/

      - name: Run tests
        run: yarn test
        working-directory: frontend/
